'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.WebService1Soap")>  _
    Public Interface WebService1Soap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Suma", ReplyAction:="*")>  _
        Function Suma(ByVal nro1 As Double, ByVal nr2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Suma", ReplyAction:="*")>  _
        Function SumaAsync(ByVal nro1 As Double, ByVal nr2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Fact", ReplyAction:="*")>  _
        Function Fact(ByVal n As Integer) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Fact", ReplyAction:="*")>  _
        Function FactAsync(ByVal n As Integer) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Resta", ReplyAction:="*")>  _
        Function Resta(ByVal nro1 As Double, ByVal nr2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Resta", ReplyAction:="*")>  _
        Function RestaAsync(ByVal nro1 As Double, ByVal nr2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Multipllicar", ReplyAction:="*")>  _
        Function Multipllicar(ByVal nro1 As Double, ByVal nr2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Multipllicar", ReplyAction:="*")>  _
        Function MultipllicarAsync(ByVal nro1 As Double, ByVal nr2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Division", ReplyAction:="*")>  _
        Function Division(ByVal nro1 As Double, ByVal nr2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Division", ReplyAction:="*")>  _
        Function DivisionAsync(ByVal nro1 As Double, ByVal nr2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Potencia", ReplyAction:="*")>  _
        Function Potencia(ByVal nro1 As Double, ByVal nr2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Potencia", ReplyAction:="*")>  _
        Function PotenciaAsync(ByVal nro1 As Double, ByVal nr2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Raiz", ReplyAction:="*")>  _
        Function Raiz(ByVal nro1 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Raiz", ReplyAction:="*")>  _
        Function RaizAsync(ByVal nro1 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Minimo", ReplyAction:="*")>  _
        Function Minimo(ByVal nro1 As Double, ByVal nr2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Minimo", ReplyAction:="*")>  _
        Function MinimoAsync(ByVal nro1 As Double, ByVal nr2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Seno", ReplyAction:="*")>  _
        Function Seno(ByVal nro1 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Seno", ReplyAction:="*")>  _
        Function SenoAsync(ByVal nro1 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Coseno", ReplyAction:="*")>  _
        Function Coseno(ByVal nro1 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Coseno", ReplyAction:="*")>  _
        Function CosenoAsync(ByVal nro1 As Double) As System.Threading.Tasks.Task(Of Double)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebService1SoapChannel
        Inherits ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebService1SoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.WebService1Soap)
        Implements ServiceReference1.WebService1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Suma(ByVal nro1 As Double, ByVal nr2 As Double) As Double Implements ServiceReference1.WebService1Soap.Suma
            Return MyBase.Channel.Suma(nro1, nr2)
        End Function
        
        Public Function SumaAsync(ByVal nro1 As Double, ByVal nr2 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.SumaAsync
            Return MyBase.Channel.SumaAsync(nro1, nr2)
        End Function
        
        Public Function Fact(ByVal n As Integer) As Double Implements ServiceReference1.WebService1Soap.Fact
            Return MyBase.Channel.Fact(n)
        End Function
        
        Public Function FactAsync(ByVal n As Integer) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.FactAsync
            Return MyBase.Channel.FactAsync(n)
        End Function
        
        Public Function Resta(ByVal nro1 As Double, ByVal nr2 As Double) As Double Implements ServiceReference1.WebService1Soap.Resta
            Return MyBase.Channel.Resta(nro1, nr2)
        End Function
        
        Public Function RestaAsync(ByVal nro1 As Double, ByVal nr2 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.RestaAsync
            Return MyBase.Channel.RestaAsync(nro1, nr2)
        End Function
        
        Public Function Multipllicar(ByVal nro1 As Double, ByVal nr2 As Double) As Double Implements ServiceReference1.WebService1Soap.Multipllicar
            Return MyBase.Channel.Multipllicar(nro1, nr2)
        End Function
        
        Public Function MultipllicarAsync(ByVal nro1 As Double, ByVal nr2 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.MultipllicarAsync
            Return MyBase.Channel.MultipllicarAsync(nro1, nr2)
        End Function
        
        Public Function Division(ByVal nro1 As Double, ByVal nr2 As Double) As Double Implements ServiceReference1.WebService1Soap.Division
            Return MyBase.Channel.Division(nro1, nr2)
        End Function
        
        Public Function DivisionAsync(ByVal nro1 As Double, ByVal nr2 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.DivisionAsync
            Return MyBase.Channel.DivisionAsync(nro1, nr2)
        End Function
        
        Public Function Potencia(ByVal nro1 As Double, ByVal nr2 As Double) As Double Implements ServiceReference1.WebService1Soap.Potencia
            Return MyBase.Channel.Potencia(nro1, nr2)
        End Function
        
        Public Function PotenciaAsync(ByVal nro1 As Double, ByVal nr2 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.PotenciaAsync
            Return MyBase.Channel.PotenciaAsync(nro1, nr2)
        End Function
        
        Public Function Raiz(ByVal nro1 As Double) As Double Implements ServiceReference1.WebService1Soap.Raiz
            Return MyBase.Channel.Raiz(nro1)
        End Function
        
        Public Function RaizAsync(ByVal nro1 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.RaizAsync
            Return MyBase.Channel.RaizAsync(nro1)
        End Function
        
        Public Function Minimo(ByVal nro1 As Double, ByVal nr2 As Double) As Double Implements ServiceReference1.WebService1Soap.Minimo
            Return MyBase.Channel.Minimo(nro1, nr2)
        End Function
        
        Public Function MinimoAsync(ByVal nro1 As Double, ByVal nr2 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.MinimoAsync
            Return MyBase.Channel.MinimoAsync(nro1, nr2)
        End Function
        
        Public Function Seno(ByVal nro1 As Double) As Double Implements ServiceReference1.WebService1Soap.Seno
            Return MyBase.Channel.Seno(nro1)
        End Function
        
        Public Function SenoAsync(ByVal nro1 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.SenoAsync
            Return MyBase.Channel.SenoAsync(nro1)
        End Function
        
        Public Function Coseno(ByVal nro1 As Double) As Double Implements ServiceReference1.WebService1Soap.Coseno
            Return MyBase.Channel.Coseno(nro1)
        End Function
        
        Public Function CosenoAsync(ByVal nro1 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.CosenoAsync
            Return MyBase.Channel.CosenoAsync(nro1)
        End Function
    End Class
End Namespace
